name: docs-publish

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docs-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
      with:
        fetch-tags: true
        fetch-depth: 0
    - name: checkout repo under _pages/
      uses: actions/checkout@main
      with:
        ref: gh-pages
        path: _pages
    - name: publish docs
      run: make docs-publish
      env:
        GIT_AUTHOR_NAME: "github-actions[bot]"
        GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        GIT_COMMITTER_NAME: "github-actions[bot]"
        GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
